export const ACTION_TYPES = {
    SET_USER: 'SET_USER',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    IS_SIGNED_IN: 'IS_SIGNED_IN',
    DELETE_USER: 'DELETE_USER',

    GET_PRODUCTS_ARRAY: 'GET_PRODUCTS_ARRAY',
    ADD_GAME_TO_PRODUCTS: 'ADD_GAME_TO_PRODUCTS',
    GET_FILTERED_PRODUCTS: 'GET_FILTERED_PRODUCTS',

    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CURRENT_GAME_CARD: 'CURRENT_GAME_CARD',
}