export const ACTION_TYPES = {
    GET_USERS: 'GET_USERS',
    SET_USER: 'SET_USER',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    IS_SIGNED_IN: 'IS_SIGNED_IN',
    DELETE_USER: 'DELETE_USER',
    GET_PRODUCTS: 'GET_PRODUCTS',
}