export const ACTION_TYPES = {
    GET_USERS: 'GET_USERS',
    SET_USER: 'SET_USER',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    IS_SIGNED_IN: 'IS_SIGNED_IN',
    DELETE_USER: 'DELETE_USER',
    GET_FILTERED_PRODUCTS: 'GET_FILTERED_PRODUCTS',

    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
}